# ~/.bashrc

# Before doing anything, replace OSX terminal tools
# with gnu tools
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

SCRIPT_DIR="$( cd "$( dirname $(readlink -e "${BASH_SOURCE[0]}") )" && pwd )"

source $SCRIPT_DIR/git-prompt.sh
source $SCRIPT_DIR/exports
source $SCRIPT_DIR/aliases
source $SCRIPT_DIR/prompts
source $SCRIPT_DIR/functions

export PATH=$PATH:$SCRIPT_DIR/../bin

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

set completion-ignore-case on
bind '"\t": menu-complete'
bind '"\e[Z": complete'

# autojump setting
if type "brew" 2>/dev/null 1>/dev/null; then
  [[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
fi

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
